/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amusic;

import amusic.clas.FileTypeFilter;
import amusic.clas.BaiHat;
import jaco.mp3.player.MP3Player;
import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.Line;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.Mixer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Dang Khoi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    MP3Player player=new MP3Player();
    ArrayList<BaiHat> bh=new ArrayList<BaiHat>();
    DefaultListModel dl=new DefaultListModel();
    int n=0;
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        hienDS();
        jSlider1.setVisible(false);
    }
    private void hienDS(){
        try {
            File f=new File("BaiHat.txt");
            Scanner sc=new Scanner(f);
            while (sc.hasNext()) {
                BaiHat a=new BaiHat(sc.nextLine(), sc.nextLine());
                bh.add(a);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        for(BaiHat as:bh){
            String s=as.getTenBai();
            String[] arr=s.split(".mp3");
            dl.addElement(arr[0]);
            list.setModel(dl);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMode = new javax.swing.JLabel();
        volum = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnBack = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btnStop = new javax.swing.JLabel();
        btnRepeat = new javax.swing.JLabel();
        txtPlay = new javax.swing.JLabel();
        txtRepeat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHien = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jSlider1 = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(230, 171, 255), new java.awt.Color(230, 171, 255), new java.awt.Color(142, 191, 255), new java.awt.Color(142, 191, 255)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/cancel_48px.png"))); // NOI18N
        jLabel1.setToolTipText("Close");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/expand_arrow_48px.png"))); // NOI18N
        jLabel2.setToolTipText("Minimize");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 191, 255)));
        jPanel5.setForeground(new java.awt.Color(0, 153, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(86, 78, 255));
        jLabel5.setText(" Mode: ");

        txtMode.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtMode.setForeground(new java.awt.Color(86, 78, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMode, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        volum.setText("1");
        volum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(volum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(volum)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/ad.gif"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(230, 171, 255), new java.awt.Color(230, 171, 255), new java.awt.Color(142, 191, 255), new java.awt.Color(142, 191, 255)));

        btnPlay.setBackground(new java.awt.Color(0, 0, 0));
        btnPlay.setFont(new java.awt.Font("Segoe Script", 0, 13)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(142, 191, 255));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png"))); // NOI18N
        btnPlay.setToolTipText("Play");
        btnPlay.setBorder(null);
        btnPlay.setContentAreaFilled(false);
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPlayKeyPressed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/rewind_30px.png"))); // NOI18N
        btnBack.setToolTipText("Previous");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/fast_forward_30px.png"))); // NOI18N
        btnNext.setToolTipText("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/stop_30px.png"))); // NOI18N
        btnStop.setToolTipText("Stop");
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopMouseClicked(evt);
            }
        });

        btnRepeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/repeat_30px.png"))); // NOI18N
        btnRepeat.setToolTipText("Repeat off");
        btnRepeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRepeatMouseClicked(evt);
            }
        });

        txtPlay.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        txtPlay.setForeground(new java.awt.Color(0, 153, 0));
        txtPlay.setText("1");

        txtRepeat.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        txtRepeat.setText("1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(txtPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStop)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(11, 11, 11)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addGap(18, 18, 18)
                .addComponent(btnRepeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRepeat, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRepeat))))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/kk.gif"))); // NOI18N

        txtHien.setEditable(false);
        txtHien.setBackground(new java.awt.Color(0, 0, 0));
        txtHien.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        txtHien.setForeground(new java.awt.Color(230, 171, 255));
        txtHien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHien.setText("Hello !!!");
        txtHien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(159, 59, 255), new java.awt.Color(159, 59, 255), new java.awt.Color(86, 78, 255), new java.awt.Color(86, 78, 255)));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list.setBackground(new java.awt.Color(0, 0, 0));
        list.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        list.setForeground(new java.awt.Color(142, 191, 255));
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 250));

        jSlider1.setBackground(new java.awt.Color(0, 0, 0));
        jSlider1.setForeground(new java.awt.Color(0, 153, 0));
        jSlider1.setMaximum(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel7.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 22, 39));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(142, 191, 255), new java.awt.Color(142, 191, 255), new java.awt.Color(230, 171, 255), new java.awt.Color(230, 171, 255)));
        jPanel6.setPreferredSize(new java.awt.Dimension(270, 47));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/11111aaa.gif"))); // NOI18N
        btnAdd.setToolTipText("Add Song");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/change_30px.png"))); // NOI18N
        jButton1.setToolTipText("Change Mode");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/trash_30px.png"))); // NOI18N
        jButton2.setToolTipText("Remove All");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/audio_25px.png"))); // NOI18N
        jLabel7.setToolTipText("Volume");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amusic/img/heart_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 310, 47));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHien, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHien, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int x,y;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        if(txtPlay.getText().equalsIgnoreCase("2")==true){
            player.stop();
        }
        
        String s= list.getSelectedValue();
        for(BaiHat as:bh){
            if(as.getTenBai().equalsIgnoreCase(s+".mp3")==true){
                player=new MP3Player();
                File f=new File(as.getDuongDan());
                player.addToPlayList(f);
                player.play();
                btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
                txtPlay.setText("2");
                txtHien.setText(s);
                txtMode.setText("manual");
                btnPlay.setToolTipText("Pause");
            }
        }
        
        try {
            File f=new File("BaiHat.txt");
            PrintWriter pr=new PrintWriter(f);
            for(BaiHat as:bh){
                pr.println(as.toString());
            }
            pr.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_listMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       JFileChooser jf=new JFileChooser();
       jf.setFileFilter(new FileTypeFilter(".mp3", "Open MP3 Files Only!"));
       if(jf.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
           try {
               File f=jf.getSelectedFile();
               
               String s=f.getName();
               String s1=f.getCanonicalPath();
               BaiHat b=new BaiHat(s, s1);
               bh.add(b);
               String[] arr=s.split(".mp3");
               txtHien.setText(arr[0]);
               dl.addElement(arr[0]);
               list.setModel(dl);
           } catch (Exception e) {
               System.out.println(e);
           }
       }
        try {
            File f=new File("BaiHat.txt");
            PrintWriter pr=new PrintWriter(f);
            for(BaiHat as:bh){
                pr.println(as.toString());
            }
            pr.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseClicked
        if(txtMode.getText().equalsIgnoreCase("auto")==true){
            player.stop();
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png")));
            txtPlay.setText("1");
            txtHien.setText("Have a nice song!!!!");
        }
        else if(txtMode.getText().equalsIgnoreCase("manual")==true){
            player.stop();
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png")));
            txtPlay.setText("1");
            txtHien.setText("Have a nice song!!!!");
        }
    }//GEN-LAST:event_btnStopMouseClicked

    private void btnRepeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRepeatMouseClicked
        if(txtRepeat.getText().equals("1")==true){
            btnRepeat.setIcon(new ImageIcon(getClass().getResource("/amusic/img/repeat_30pxk.png")));
            txtRepeat.setText("2");
            player.setRepeat(false);
            btnRepeat.setToolTipText("Repeat on");
        }
        else if(txtRepeat.getText().equals("2")==true){
            btnRepeat.setIcon(new ImageIcon(getClass().getResource("/amusic/img/repeat_30px.png")));
            txtRepeat.setText("1");
            player.setRepeat(true);
            btnRepeat.setToolTipText("Repeat off");
        }
    }//GEN-LAST:event_btnRepeatMouseClicked

    private void btnPlayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPlayKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayKeyPressed

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
       n++;
       ArrayList<String> ar=new ArrayList<String>();
       String s="";
       if(txtMode.getText().length()==0){
           for(BaiHat as:bh){
               ar.add(as.getTenBai());
           }
           
           for(int i=0;i<ar.size();i++){
               s=ar.get(0);
           }
           
           for(BaiHat as:bh){
               if(as.getTenBai().equalsIgnoreCase(s)==true){
                   player=new MP3Player();
                   File f=new File(as.getDuongDan());
                   player.addToPlayList(f);
                   player.play();
               }
           }
           
           String[] arr=s.split(".mp3");
           list.setSelectedValue(arr[0], true);
           txtHien.setText(arr[0]);
           btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
           txtPlay.setText("2");
           btnPlay.setToolTipText("Pause");
           txtMode.setText("manual");
       }
       else if(txtMode.getText().equalsIgnoreCase("auto")==true){
           if(txtPlay.getText().equals("1")==true){
                player.play();
                btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
                txtPlay.setText("2");
                btnPlay.setToolTipText("Pause");
           }
            
           else if(txtPlay.getText().equals("2")==true){
               player.pause();
               btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png")));
               txtPlay.setText("1");
               btnPlay.setToolTipText("Play");
           }
       }
       else if(txtMode.getText().equalsIgnoreCase("manual")==true){
            if(txtPlay.getText().equalsIgnoreCase("1")==true){
                player.play();
                btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
                txtPlay.setText("2");
                btnPlay.setToolTipText("Pause");
            }
            else if(txtPlay.getText().equalsIgnoreCase("2")==true){
                player.pause();
                btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png")));
                txtPlay.setText("1");
                btnPlay.setToolTipText("Play");
            }
       }
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        if(txtMode.getText().equalsIgnoreCase("auto")==true){
            player.skipForward();
        }
        else if(txtMode.getText().equalsIgnoreCase("manual")==true){
            if(txtPlay.getText().equalsIgnoreCase("2")==true){
                player.stop();
            }
        
            ArrayList<String> st=new ArrayList<String>();
            for(BaiHat as:bh){
                st.add(as.getTenBai());
            }
        
            for(int i=0;i<st.size();i++){
                if(st.get(i).equals(txtHien.getText()+".mp3")==true){
                    String s=st.get(i+1)+"";
                    String[] arr=s.split(".mp3");
                    txtHien.setText(arr[0]);
                    list.setSelectedIndex(i+1);
                    break;
                }
                else if(st.get(st.size()-1).equals(txtHien.getText()+".mp3")==true){
                    String s=st.get(i)+"";
                    String[] arr=s.split(".mp3");
                    txtHien.setText(arr[0]);
                    list.setSelectedIndex(i);
                }
            }
        
            for(BaiHat as:bh){
                if(as.getTenBai().equalsIgnoreCase(txtHien.getText()+".mp3")){
                    player=new MP3Player();
                    File f=new File(as.getDuongDan());
                    player.addToPlayList(f);
                    player.play();
                    btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
                    txtPlay.setText("2");
                    btnPlay.setToolTipText("Pause");
                }
            }
        }
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        if(txtMode.getText().equalsIgnoreCase("auto")==true){
            player.skipBackward();
        }
        else if(txtMode.getText().equalsIgnoreCase("manual")==true){
        if(txtPlay.getText().equalsIgnoreCase("2")){
            player.stop();
        }
        
        ArrayList<String> st =new ArrayList<String>();
        ArrayList<String> st1 =new ArrayList<String>();
        for(BaiHat as:bh){
            st.add(as.getTenBai());
        }
        
        Collections.reverse(st);
        for(String as:st){
            st1.add(as);
        }
        
         for(int i=0;i<st1.size();i++){
            if(st1.get(i).equals(txtHien.getText()+".mp3")==true){
                String s=st.get(i+1)+"";
                String[] arr=s.split(".mp3");
                txtHien.setText(arr[0]);
                list.setSelectedValue(arr[0], true);
                break;
            }
            else if(st.get(st.size()-1).equals(txtHien.getText()+".mp3")==true){
                String s=st.get(i)+"";
                String[] arr=s.split(".mp3");
                txtHien.setText(arr[0]);
                list.setSelectedValue(arr[0], true);
            }
        }
        
        for(BaiHat as:bh){
            if(as.getTenBai().equalsIgnoreCase(txtHien.getText()+".mp3")){
                player=new MP3Player();
                File f=new File(as.getDuongDan());
                player.addToPlayList(f);
                player.play();
                btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
                txtPlay.setText("2");
                btnPlay.setToolTipText("Pause");
            }
            }
        }
    }//GEN-LAST:event_btnBackMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtMode.getText().equalsIgnoreCase("auto")==true){
            player.stop();
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png")));
            txtPlay.setText("1");
//            btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
//            txtPlay.setText("2");
            txtHien.setText("Have a nice song!!!!");
            btnPlay.setToolTipText("Play");
            player=new MP3Player();
//            for(BaiHat as:bh){
//                    File f=new File(as.getDuongDan());
//                    player.addToPlayList(f);
//                    player.play(); 
//                    player.setShuffle(true);
//               }
            txtMode.setText("manual");
        }
        else if(txtMode.getText().equalsIgnoreCase("manual")==true){
            player.stop();
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
            txtPlay.setText("2");
//            btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png")));
//            txtPlay.setText("1");
            txtHien.setText("Have a nice song!!!!");
            btnPlay.setToolTipText("Pause");
            txtMode.setText("auto");
            
            player=new MP3Player();
            for(BaiHat as:bh){
                    File f=new File(as.getDuongDan());
                    player.addToPlayList(f);
                    player.play(); 
                    player.setShuffle(true);
               }
            txtMode.setText("auto");
        }
        else {
            txtMode.setText("auto");
            player=new MP3Player();
            for(BaiHat as:bh){
                    File f=new File(as.getDuongDan());
                    player.addToPlayList(f);
                    player.play(); 
                    player.setShuffle(true);
               }
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/pause_button_30px.png")));
            txtPlay.setText("2");
            btnPlay.setToolTipText("Pause");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dl.removeAllElements();
        player.stop();
        txtMode.setText("");
        btnPlay.setIcon(new ImageIcon(getClass().getResource("/amusic/img/play_30pxs.png")));
        txtPlay.setText("1");
        btnPlay.setToolTipText("Play");
        bh.removeAll(bh);
        try {
            File f=new File("BaiHat.txt");
            PrintWriter pr=new PrintWriter(f);
            for(BaiHat as:bh){
                pr.println(as.toString());
            }
            pr.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void volumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumMouseClicked

    }//GEN-LAST:event_volumMouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        float valueToPlusMinus =Float.parseFloat(jSlider1.getValue()+"")/10;
        Mixer.Info[] mixers = AudioSystem.getMixerInfo();
        for(Mixer.Info mixerInfo : mixers){
            Mixer mixer = AudioSystem.getMixer(mixerInfo);
            Line.Info[] lineInfos = mixer.getTargetLineInfo();
            for(Line.Info lineInfo : lineInfos){
                Line line = null;
                boolean opened = true;
                try{
                    line = mixer.getLine(lineInfo);
                    opened = line.isOpen() || line instanceof Clip;
                    if(!opened){
                        line.open();
                    }
                    FloatControl volControl = (FloatControl) line.getControl(FloatControl.Type.VOLUME);
                    volControl.setValue((float)valueToPlusMinus);
                    
                }catch (LineUnavailableException lineException){
                }catch (IllegalArgumentException illException){
                }finally{
                    if(line != null && !opened){
                        line.close();
                    }
                }
            }
        }
    }//GEN-LAST:event_jSlider1StateChanged

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(volum.getText().equals("1")==true){
            jSlider1.setVisible(true);
            volum.setText("2");
        }
        else if(volum.getText().equals("2")==true){
            jSlider1.setVisible(false);
            volum.setText("1");
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnNext;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel btnRepeat;
    private javax.swing.JLabel btnStop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField txtHien;
    private javax.swing.JLabel txtMode;
    private javax.swing.JLabel txtPlay;
    private javax.swing.JLabel txtRepeat;
    private javax.swing.JLabel volum;
    // End of variables declaration//GEN-END:variables
}
